### ISSUE TITLE
(kind) feature request: enable loading ClojureScript source from external file

### ISSUE THREAD

**Issue by lwiechec** [borkdude/scittle#10]
I love Scittle - but I tried this:

```html
<html>
  <head>
    <script src="js/scittle.js" type="application/javascript"></script>
    <script src="js/react.production.min.js"></script>
    <script src="js/react-dom.production.min.js"></script>
    <script src="js/scittle.reagent.js" type="application/javascript"></script>
    <script type="application/x-scittle" src="my-super-scittle-sources.cljs"></script>
...
```

but the ClojureScript file was not loaded. 

My source is growing and I would love to be able to load it from the external file...

**Comment by borkdude** [comment]
This should already work. Please provide a minimal repro, e.g. a github project I can clone and run locally. Also provide the error message, if any.

**Comment by lwiechec** [comment]
oops - apologies, I must have done something incorrect. Indeed, it is working... thanks for help!
