### ISSUE TITLE
Cross origin request

### ISSUE THREAD

**Issue by AndreaCrotti** [borkdude/scittle#12]
So I was just trying to create a simple page, with the cljs file in a different file, so just something like

`<html>
  <head>
    <script src="https://cdn.jsdelivr.net/gh/borkdude/scittle@0.0.1/js/scittle.js" type="application/javascript"></script>
    <script crossorigin src="https://unpkg.com/react@17/umd/react.production.min.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js"></script>
    <script src="https://cdn.jsdelivr.net/gh/borkdude/scittle@0.0.1/js/scittle.reagent.js" type="application/javascript"></script>
    <script type="application/x-scittle" src="hello.cljs"></script>
  </head>
  <body>
    <div id="app">
    </div>
  </body>
</html>`

but it fails with an error like this:

`Access to XMLHttpRequest at 'file:....hello.cljs' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, brave, chrome-untrusted, https.`

Maybe do I need the backend to serve the resource if I use a separate file? 
From the docs and the tictactoe example I thought I didn't and could just open the HTML file locally, but maybe I'm wrong.

**Comment by borkdude** [comment]
@AndreaCrotti You might have serve the HTML using an http file server like https://github.com/babashka/babashka/blob/master/examples/http-server.clj or python -m http.server.

**Comment by AndreaCrotti** [comment]
Yeah ok sure makes sense
